r"""
physdecal yolo
The YOLO arm: dataset mirror, finetuning, and the victim wrapper.

    physdecal yolo setup            build the isolated dataset mirror
    physdecal yolo train --epochs 8
    physdecal yolo check

WHY A MIRROR RATHER THAN THE SHIPPED data.yaml
-----------------------------------------------
The dataset already carries a YOLO export, and pointing Ultralytics at it
would work -- and would also write `labels.cache` into
`airsim_city_v1/labels/`, plus run artefacts wherever it pleases. This folder
promises never to write into the dataset, and a training framework that caches
next to the labels breaks that promise silently.

So `setup` builds `out/yolo/` with the layout Ultralytics expects:

    out/yolo/images/{train,val}/   HARDLINKS to the dataset images
    out/yolo/labels/{train,val}/   copies of the label text files
    out/yolo/data.yaml

Hardlinks, not copies, for the images: the dataset is about 12,500 PNGs and
copying them would cost gigabytes for no benefit. A hardlink is a second name
for the same bytes on the same volume, costs nothing, and -- the part that
matters here -- is read-only as far as this experiment is concerned, because
nothing in the pipeline writes to an image. If the volume ever differs the
code falls back to copying rather than silently producing a broken tree.

WHY YOLO IS A TRANSFER TARGET AND NOT A WHITE-BOX ARM
------------------------------------------------------
The paper's white-box arm needs dense per-location class logits with a stable
gradient path, which `detection.DetVictim.dense_scores` provides for the
torchvision dense detectors. Ultralytics wraps its forward pass in its own
predictor with NMS and letterboxing inside, and reaching through that to a
differentiable dense map is possible but is a different piece of engineering
with its own failure modes. YOLO is therefore evaluated as a black-box
transfer target, which is also the honest role for it: it is the detector an
operational pipeline is most likely to be running, and the question the paper
asks of it is whether a patch built elsewhere defeats it.
"""

import argparse
import os
import shutil

import numpy as np
import torch

from physdecal import config as N


YOLO_ROOT = os.path.join(N.EXP_ROOT, "yolo")
WEIGHTS = os.path.join(N.FINETUNE_DIR, "yolo_vehicle.pt")


def _link_or_copy(src, dst):
    if os.path.exists(dst):
        return "skip"
    try:
        os.link(src, dst)
        return "link"
    except OSError:
        shutil.copy2(src, dst)
        return "copy"


def setup(force=False):
    """Build the isolated mirror. Idempotent."""
    if force and os.path.isdir(YOLO_ROOT):
        shutil.rmtree(YOLO_ROOT)

    counts = {"link": 0, "copy": 0, "skip": 0, "missing": 0}
    for split, listfile in (("train", "train.txt"), ("val", "holdout.txt")):
        lp = os.path.join(N.DATA_ROOT, "splits", listfile)
        if not os.path.isfile(lp):
            raise SystemExit("No %s. Run make_splits.py from the GeoPatchCity capture pipeline first." % lp)
        img_dir = os.path.join(YOLO_ROOT, "images", split)
        lab_dir = os.path.join(YOLO_ROOT, "labels", split)
        os.makedirs(img_dir, exist_ok=True)
        os.makedirs(lab_dir, exist_ok=True)

        with open(lp, encoding="utf-8") as f:
            paths = [ln.strip() for ln in f if ln.strip()]
        for src in paths:
            stem = os.path.splitext(os.path.basename(src))[0]
            if not os.path.isfile(src):
                counts["missing"] += 1
                continue
            counts[_link_or_copy(src, os.path.join(img_dir,
                                                   os.path.basename(src)))] += 1
            lab_src = os.path.join(N.DATA_ROOT, "labels", stem + ".txt")
            lab_dst = os.path.join(lab_dir, stem + ".txt")
            if os.path.isfile(lab_src):
                if not os.path.exists(lab_dst):
                    shutil.copy2(lab_src, lab_dst)
            elif not os.path.exists(lab_dst):
                # A frame with no vehicles is a legitimate empty label file,
                # not an error. Ultralytics treats a missing file as
                # "unlabelled" and an empty one as "no objects", and those are
                # different things.
                open(lab_dst, "w").close()

    yaml_p = os.path.join(YOLO_ROOT, "data.yaml")
    with open(yaml_p, "w", encoding="utf-8") as f:
        f.write("# Generated by physdecal yolo. Images are HARDLINKS to the\n"
                "# dataset; labels are copies. Nothing here writes into\n"
                "# airsim_city_v1/.\n"
                "path: %s\n"
                "train: images/train\n"
                "val: images/val\n"
                "nc: 2\n"
                "names: ['car', 'truck']\n"
                % YOLO_ROOT.replace("\\", "/"))
    print("mirror at %s" % YOLO_ROOT)
    print("  %d hardlinked, %d copied, %d already present, %d missing"
          % (counts["link"], counts["copy"], counts["skip"], counts["missing"]))
    print("  -> %s" % yaml_p)
    return yaml_p


def train(epochs=8, imgsz=1024, batch=8, model="yolov8n.pt"):
    from ultralytics import YOLO
    from ultralytics import settings as ul_settings

    yaml_p = os.path.join(YOLO_ROOT, "data.yaml")
    if not os.path.isfile(yaml_p):
        yaml_p = setup()

    # Keep every Ultralytics artefact inside out/.
    ul_settings.update({"datasets_dir": YOLO_ROOT,
                        "runs_dir": os.path.join(N.EXP_ROOT, "yolo_runs"),
                        "weights_dir": os.path.join(N.EXP_ROOT, "yolo_weights")})

    m = YOLO(model)
    m.train(data=yaml_p, epochs=epochs, imgsz=imgsz, batch=batch,
            project=os.path.join(N.EXP_ROOT, "yolo_runs"), name="vehicle",
            exist_ok=True, seed=N.SEED, verbose=True, plots=False,
            val=True, deterministic=False)
    best = os.path.join(N.EXP_ROOT, "yolo_runs", "vehicle", "weights", "best.pt")
    if os.path.isfile(best):
        os.makedirs(N.FINETUNE_DIR, exist_ok=True)
        shutil.copy2(best, WEIGHTS)
        print("\nbest weights -> %s" % WEIGHTS)
    return WEIGHTS


class YoloVictim:
    """
    Black-box transfer target with the same predict() contract as
    detection.DetVictim, so evaluate.py needs no special case.

    Returns torchvision-style dicts: boxes xyxy in the ORIGINAL image pixels,
    scores, labels. Labels are mapped to the binary convention the finetuned
    torchvision heads use -- 1 for vehicle -- so `vehicle_ids` means the same
    thing across every detector in the roster.
    """

    key = "yolo"
    density = "black_box"
    finetuned = True

    def __init__(self, weights=None, device=None):
        from ultralytics import YOLO
        w = weights or WEIGHTS
        if not os.path.isfile(w):
            raise SystemExit(
                "No %s.\nTrain the YOLO arm first:\n"
                "  physdecal yolo train" % w)
        self.net = YOLO(w)
        self.device = device or N.DEVICE

    def vehicle_ids(self, dataset_class="car"):
        return [1]

    @torch.no_grad()
    def predict(self, images):
        out = []
        for im in images:
            arr = (im.detach().cpu().permute(1, 2, 0).numpy() * 255)
            arr = np.clip(arr, 0, 255).astype(np.uint8)[:, :, ::-1]  # RGB->BGR
            r = self.net.predict(arr, verbose=False, device=self.device,
                                 imgsz=N.DET_INPUT_LONG_SIDE)[0]
            b = r.boxes
            if b is None or len(b) == 0:
                out.append({"boxes": torch.zeros(0, 4),
                            "scores": torch.zeros(0),
                            "labels": torch.zeros(0, dtype=torch.int64)})
                continue
            # Both YOLO classes (car, truck) are vehicles; collapse to 1 so the
            # roster shares one vehicle id.
            out.append({"boxes": b.xyxy.cpu(),
                        "scores": b.conf.cpu(),
                        "labels": torch.ones(len(b), dtype=torch.int64)})
        return out

    def to(self, *a, **k):
        return self

    def eval(self):
        return self


def check():
    print("mirror     :", YOLO_ROOT,
          "(present)" if os.path.isdir(YOLO_ROOT) else "(not built)")
    print("weights    :", WEIGHTS,
          "(present)" if os.path.isfile(WEIGHTS) else "(not trained)")
    for split in ("train", "val"):
        d = os.path.join(YOLO_ROOT, "images", split)
        n = len(os.listdir(d)) if os.path.isdir(d) else 0
        print("  %-5s images: %d" % (split, n))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("setup").add_argument("--force", action="store_true")
    t = sub.add_parser("train")
    t.add_argument("--epochs", type=int, default=8)
    t.add_argument("--imgsz", type=int, default=1024)
    t.add_argument("--batch", type=int, default=8)
    t.add_argument("--model", default="yolov8n.pt")
    sub.add_parser("check")
    a = ap.parse_args()

    if a.cmd == "setup":
        setup(a.force)
    elif a.cmd == "train":
        train(a.epochs, a.imgsz, a.batch, a.model)
    else:
        check()


if __name__ == "__main__":
    main()
